SET SESSION group_concat_max_len = 100000000;

SELECT GROUP_CONCAT(CONCAT('\t', COLUMN_NAME, ',') ORDER BY ORDINAL_POSITION SEPARATOR '\n') AS column_list
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'crmmedivant'
  AND TABLE_NAME = 'emailtemplate';
  
-- SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY ORDINAL_POSITION SEPARATOR ', ') AS column_list
-- FROM INFORMATION_SCHEMA.COLUMNS
-- WHERE TABLE_SCHEMA = 'crmmedivant'
--   AND TABLE_NAME = 'leadmst';